version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    depends_on: []
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:80"
    depends_on:
      - backend
